### ISSUE TITLE
Missing "expand" feature on Run page

### ISSUE THREAD

**Issue by zmc** [ceph/pulpito-ng#48]
In the original Pulpito, we can click on rows in job tables (on run pages) to expand them, showing the failure reason. We also have a button that expands all of them at once.

MUI's DataGrid keeps that feature locked behind their paid, non-MIT-licensed version. That's not an option for us, so we'd likely need to use a different component to render tables.

There's a pretty complete comparison of the options here: https://www.material-react-table.com/#let's-compare

That project (material-react-table) might do what we want. It looks like they are inching close to a V2 release, with a very large changeset looming. Once that release is out maybe we should try that.

**Comment by VallariAg** [comment]
@zmc Looks like V2 is finally out: https://www.material-react-table.com/ 🎉 
announcement blog: https://www.material-react-table.com/blog/announcing-material-react-table-v2
