### ISSUE TITLE
Links with many jobs on them are a bit slow to load

### ISSUE THREAD

**Issue by ljflores** [ceph/pulpito-ng#54]
Example link: https://pulpito-ng.ceph.com/runs/yuriw-2023-08-08_14:45:33-rados-wip-yuri6-testing-2023-08-03-0807-pacific-distro-default-smithi

Took about 4 seconds to load. Not crazy bad, but enough to notice.

**Comment by zmc** [comment]
Slower than with the original pulpito?

**Comment by ljflores** [comment]
Yeah, now that I'm comparing it to the original, the original does take a few seconds to load too, which I always attributed to the VPN. I'll close this since it's not a huge issue, and it is comparable to the original.

**Comment by zmc** [comment]
The response time is definitely not ideal, and I think we could do something about it on the paddles side by omitting certain parts of the job objects we return as part of a run object.
