### ISSUE TITLE
Missing "job stats" information

### ISSUE THREAD

**Issue by ljflores** [ceph/pulpito-ng#55]
On the Run page, it would be good to have the overall Job Stats as shown in this screenshot (the "Job Stats for this page" line):
![image](https://github.com/ceph/pulpito-ng/assets/64499477/3dc5b0e2-954a-4d55-9e81-f7b63db804c2)

On the Job page, it would again be good to see an overview of passed, failed, running, queued, etc. jobs as shown by the dark red and green text boxes.
![image](https://github.com/ceph/pulpito-ng/assets/64499477/9e04a6f0-0bd2-46df-8c02-2b994758cb0d)

**Comment by kamoltat** [comment]
Hi Laura,
are you talking about this:

![image](https://github.com/ceph/pulpito-ng/assets/22287000/4717c771-b033-4b30-ab64-cb7829273e31)


https://pulpito-ng.ceph.com/runs/yuriw-2023-10-03_16:08:12-rados-wip-yuri5-testing-2023-09-27-0959-distro-default-smithi

@ljflores

**Comment by ljflores** [comment]
@kamoltat I mean these specific details:

![image](https://github.com/ceph/pulpito-ng/assets/64499477/290696d6-ab83-4eca-ba8b-938875cded9d)
![image](https://github.com/ceph/pulpito-ng/assets/64499477/6d2058ef-ac7b-4795-9ad6-a347abfd47ca)

Where you can see an overview of x number of jobs in any particular state.

**Comment by kamoltat** [comment]
This has been resolved by https://github.com/ceph/pulpito-ng/pull/64
