### ISSUE TITLE
Node page sorting breaks queries

### ISSUE THREAD

**Issue by zmc** [ceph/pulpito-ng#61]
Starting from e.g. `/nodes?machine_type=smithi`, if you attempt to use the `DataGrid` filter feature, you're immediately redirected to `/nodes`, dropping the `machine_type` query.

**Comment by kamoltat** [comment]
@zmc I tried reproducing this issue, but couldn't seem to do so in main, is this fixed?

**Comment by kamoltat** [comment]
Might not be able to fix this, since https://github.com/ceph/pulpito-ng/pull/49 will be changing DataGrid to material-react-table
