### ISSUE TITLE
Search for part of job description across other runs 

### ISSUE THREAD

**Issue by VallariAg** [ceph/pulpito-ng#88]
Users see a job fail and have to look up different runs to see if the run is failing on other branches (to see if it's a common bug or local to their run). They sometimes have to `grep` last 50-something runs to see if the problem is in other runs. 

We can probably include a feature to search for string of job description across runs. This change requires paddles to support such a query.

**Comment by kamoltat** [comment]
@adk3798 @ronen-fr

**Comment by ronen-fr** [comment]
@kamoltat - even before that: I could not find that string (the description) at all when listing a specific run?

**Comment by VallariAg** [comment]
@ronen-fr If you're looking for all job descriptions of a run, it's possible on pulpito-ng by toggling the "description" column:

https://github.com/user-attachments/assets/3e9c1d4f-cc40-4faa-868c-764c5c64717c

It's also possible on current pulpito: try clicking "Show Description" button on https://pulpito.ceph.com/teuthology-2024-09-25_21:24:35-fs-squid-distro-default-smithi/

**Comment by ronen-fr** [comment]
thanks. I missed that.
I know, of course, how to do it in the current pulpito...

**Comment by ronen-fr** [comment]
Ah, I wasn't totally dumb. Here is how it looks in [deploy-preview-87--pulpito.netlify.app](https://deploy-preview-87--pulpito.netlify.app/runs/rfriedma-2024-09-25_15:39:13-rados:thrash-wip-rf-59944-reef-distro-default-smithi)
(the other new Pulpito link you showed):
 
![Screenshot_20240926_213921](https://github.com/user-attachments/assets/585ac9ec-e6ed-49d2-b4dd-d5b48ebcc8ad)

No description field

**Comment by VallariAg** [comment]
@ronen-fr So sorry, it's my bad! That URL is a temporary URL for user-filter feature (it will stop working after the username PR is merged). It's not rebased to latest main that's why it didn't had description and task fields. I have rebased it now, you should be able to see description in above URL too.

The actual pulpito-ng deployment is at https://pulpito-ng.ceph.com/. It doesn't have the global search and username filter yet, I will update you here when it does. Sorry for the confusion!
