### ISSUE TITLE
Year of the date in general should be "2023" not "23"

### ISSUE THREAD

**Issue by kamoltat** [ceph/pulpito-ng#9]
![image](https://github.com/zmc/pulpito-ng/assets/22287000/34f84254-d1e3-45c7-b372-73bdc6491206)

**Comment by Devansh3712** [comment]
On changing the `formatDate` function in `src/lib/utils.js` the year will be in the `yyyy-mm-dd` format.

![image](https://github.com/ceph/pulpito-ng/assets/58616444/f4aab082-a300-4a10-a516-a47e21d9073d)
